package pt.deliveries.business_initiative.selenium;


// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class ClientRegisterAndCreatesOrder {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void ClientResgitersLogsAndCreatesAnOrder() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1853, 2553));
    driver.findElement(By.linkText("Don\'t have an account? Sign Up")).click();
    driver.findElement(By.id("name")).sendKeys("cunha");
    driver.findElement(By.id("email")).sendKeys("cunha1234@ua.pt");
    driver.findElement(By.id("password")).sendKeys("1234");
    driver.findElement(By.id("phoneNumber")).sendKeys("961234");
    driver.findElement(By.id("outlined-age-native-simple")).click();
    {
      WebElement dropdown = driver.findElement(By.id("outlined-age-native-simple"));
      dropdown.findElement(By.xpath("//option[. = 'Male']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    js.executeScript("window.scrollTo(0,0)");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    driver.findElement(By.id("formLoginEmail")).sendKeys("cunha1234@ua.pt");
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.id("formLoginPassword")).sendKeys("1234");
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("signInButton")).click();
    driver.findElement(By.id("qnty")).sendKeys("1");
    driver.findElement(By.id("qnty")).click();
    driver.findElement(By.id("qnty")).sendKeys("2");
    driver.findElement(By.id("qnty")).click();
    {
      WebElement element = driver.findElement(By.id("qnty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("qnty")).sendKeys("3");
    driver.findElement(By.id("qnty")).click();
    driver.findElement(By.id("qnty")).sendKeys("4");
    driver.findElement(By.id("qnty")).click();
    driver.findElement(By.id("qnty")).sendKeys("5");
    driver.findElement(By.id("qnty")).click();
    driver.findElement(By.cssSelector(".card:nth-child(1) button")).click();
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).sendKeys("-1");
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).click();
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).sendKeys("-2");
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).click();
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).sendKeys("-1");
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).click();
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).sendKeys("0");
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".card:nth-child(2) #qnty"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).sendKeys("1");
    driver.findElement(By.cssSelector(".card:nth-child(2) #qnty")).click();
    driver.findElement(By.cssSelector(".card:nth-child(2) button")).click();
    driver.findElement(By.cssSelector(".nav-item:nth-child(3) .material-icons")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector(".modal-body button")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".modal-body button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("cityInput")).click();
    driver.findElement(By.id("cityInput")).sendKeys("city");
    driver.findElement(By.id("completeAddressInput")).click();
    driver.findElement(By.id("completeAddressInput")).sendKeys("addresss");
    driver.findElement(By.id("latitudeInput")).click();
    driver.findElement(By.id("latitudeInput")).sendKeys("lat");
    driver.findElement(By.id("longitudeInput")).click();
    driver.findElement(By.id("longitudeInput")).sendKeys("long");
    driver.findElement(By.cssSelector(".col-3 > button")).click();
    driver.findElement(By.id("latitudeInput")).click();
    driver.findElement(By.id("latitudeInput")).sendKeys("1234");
    driver.findElement(By.id("longitudeInput")).click();
    driver.findElement(By.id("longitudeInput")).click();
    driver.findElement(By.id("longitudeInput")).click();
    {
      WebElement element = driver.findElement(By.id("longitudeInput"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("longitudeInput")).click();
    driver.findElement(By.id("longitudeInput")).sendKeys("1234");
    driver.findElement(By.cssSelector(".col-3 > button")).click();
    driver.findElement(By.cssSelector(".MuiTableCell-alignCenter")).click();
    driver.findElement(By.name("fav_language")).click();
    {
      WebElement element = driver.findElement(By.name("fav_language"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".modal-footer > button:nth-child(2)")).click();
    driver.findElement(By.linkText("Profile")).click();
    driver.findElement(By.cssSelector(".cards__item:nth-child(2) .cards__item__img")).click();
  }
}