name: ci-BusinessInicative

on:
  push:
    branches:
      - '**'
    paths:
      - BusinessInicative/**
  
  pull_request:
      branches:
        - main
        - develop
      paths:  
        - BusinessInicative/**


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
   
    - name: entry BusinessInicative
      run: cd BusinessInicative

    - name: Build with Maven
      run: mvn -B package --file pom.xml
