# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ main, cd-test-deploy ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted

    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup BusinessInitiative database
        run: |
          docker stop business-mysql 2>/dev/null
          docker start business-mysql

      - name: Setup BusinessInitiative
        run: |
          export MYSQL_DB="jdbc:mysql://business-mysql:3306/business-mysql"
          cd BusinessInitiative
          ./mvnw package -DskipTests
          docker stop business-initiative 2>/dev/null
          docker rm business-initiative 2>/dev/null
          docker build -t business-initiative .
          docker run -d -p 8090:8090 --name business-initiative --link business-mysql:mysql business-initiative

      - name: Setup DeliveriesEngine database
        run: |
          docker stop deliveries-mysql 2>/dev/null
          docker start deliveries-mysql

      - name: Setup DeliveriesEngine
        run: |
          export MYSQL_DB="jdbc:mysql://deliveries-mysql:3305/deliveries-mysql"
          cd DeliveriesEngine
          ./mvnw package -DskipTests
          docker stop deliveries-engine 2>/dev/null
          docker rm deliveries-engine 2>/dev/null
          docker build -t deliveries-engine .
          docker run -p 8089:8089 --name deliveries-engine --link deliveries-mysql:mysql deliveries-engine



    
