# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ main, cd-test-deploy ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted

    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup BusinessInitiative database
        run: |
          docker stop business-mysql 2>/dev/null
          docker start business-mysql

      - name: Setup BusinessInitiative
        run: |
          cd BusinessInitiative
          kill -9 $(lsof -t -i:8090) 2>/dev/null
          if lsof -t -i:8090; then kill -9 $(lsof -t -i:8090); fi
          nohup ./mvnw spring-boot:run > app.log 2>&1 &
          echo $! > run.pid


#      - name: Setup DeliveriesEngine database
#        run: |
#          docker stop deliveries-mysql 2>/dev/null
#          docker start deliveries-mysql
#
#      - name: Setup DeliveriesEngine
#        run: |
#          export MYSQL_DB="jdbc:mysql://deliveries-mysql:3305/deliveries-mysql"
#          cd DeliveriesEngine
#          echo biodrop | sudo -S kill -9 $(sudo lsof -t -i:8089)
#          nohup ./mvnw spring-boot:run > app.log 2>&1 &
#          echo $! > run.pid



    
