# This is a basic workflow to help you get started with Actions

name: Deploy
on:
  push:
    branches: [ main, cd-test-deploy ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: self-hosted

    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup BusinessInitiative database
        run: |
          docker stop business-mysql 2>/dev/null
          docker start business-mysql

      - name: Setup BusinessInitiative
        run: |
          cd BusinessInitiative
          ./mvnw package -DskipTests
          docker stop business-initiative 2>/dev/null
          docker rm business-initiative 2>/dev/null
          docker build -t business-initiative .
          docker run -d -p 8090:8090 --name business-initiative --link business-mysql:mysql business-initiative



        


        
        
        
        
        
        
        
